# Generated by Django 5.0 on 2024-07-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mansets',
            old_name='üstyazi',
            new_name='ustyazi',
        ),
    ]
