# Generated by Django 5.0 on 2024-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0003_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='mansets',
            name='resim',
            field=models.ImageField(default='assets/images/istanbul.jpg', upload_to='static/assets/images/%Y/%m/%d/'),
        ),
    ]
