# Generated by Django 5.0 on 2024-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0004_mansets_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mansets',
            name='resim',
            field=models.ImageField(default='static/assets/images/istanbul.jpg', upload_to='static/assets/images/%Y/%m/%d/'),
        ),
    ]
