# Generated by Django 5.0 on 2024-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('file_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='mansets',
            name='resim',
            field=models.ImageField(upload_to='static/assets/images/%Y/%m/%d/'),
        ),
    ]
