# Generated by Django 5.0 on 2024-07-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0008_files_alter_mansets_resim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='files',
        ),
    ]
